#!/bin/bash
clear
echo "   _____  _____    _____  _____                       "
echo "  / ____||  __ \  / ____|/ ____|                      "
echo " | (___  | |  | || |    | |                           "
echo "  \___ \ | |  | || |    | |                           "
echo "  ____) || |__| || |____| |____                       "
echo " |_____/ |_____/  \_____|\_____|                      "
echo "                                                      "
echo "                                                      "
echo "  _              _                           _        "
echo " | |            | |                         | |       "
echo " | |_  ___  ___ | |_   _ __ ___    ___    __| |  ___  "
echo " | __|/ _ \/ __ | __| | |_   _ \  / _ \  / _  | / _ \ "
echo " | |_|  __/\__ \| |_  | | | | | || (_) || (_| ||  __/ "
echo "  \__|\___||___/ \__| |_| |_| |_| \___/  \__ _| \___| "
echo "                                                      "
echo "                                                      "
echo -ne '                          (0%) starting flink dispatcher \r'
sleep 1
echo -ne '#####                     (25%) starting controller      \r'
mvn install:install-file -Dfile=../entities/pom.xml -DgroupId=entities -DartifactId=entities -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -e
java Runner
echo -ne '#############             (50%) starting semapores       \r'
sleep 1
echo -ne '#######################   (75%) starting IoT simulation  \r'
sleep 1
echo -ne '######################### (100%) test run with success ! \r'
echo -ne '\n'
